title: Shrimp World
description: A blog about my 5 gallon no filter planted tank. 
author: Heming
url: "https://h3ming.github.io"
baseurl: "/ShrimpWorld"
markdown: kramdown 
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-paginate
paginate: 7
paginate_path: "/page:num/"